// next
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

// styles
import styles from '../styles/Home.module.css';

// components
import Container from '../components/Container';
import Badge from '../components/Badge';
import SkillsContainer from '../components/SkillsContainer';
import ProjectList from '../components/ProjectList';
import PostList from '../components/PostList';
import MiniPostCard from '../components/MiniPostCard';

// libs
import { getGithubProfilePic } from '../libs/info';
import { DefaultProps, MiniPost, Skill, Project, Status } from '../libs/types';

// data consumption
import { CONTACT_LIST } from '../libs/contact';
import { getAllSkills } from '../libs/skills';
import { getAllPostPreviewsAsMiniPosts } from '../libs/post';
import { getAllProjects } from '../libs/project';
import { getSingleRandomStatus } from '../libs/status';

interface Props extends DefaultProps {
	avatarUrl?: string;
	status: Status;
	posts: MiniPost[];
	skills: Skill[];
	projects: Project[];
};

const Home: NextPage<Props> = (props) => {
  return (
	<Container>
		<Head>
			<title>Portfolio do Leonardo</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>
			<div className={styles.personalInfo}>
				<div className={styles.profileWrapper}>
					{
						props.avatarUrl
						? (
							<Image
								className={styles.profilePic}
								src={props.avatarUrl}
								alt="Leo's Github profile picture"
								width="250px"
								height="250px"
							/>
						)
						: null
					}

					<div className={styles.profileStatus}>
						<Image
							src={props.status.src}
							alt="Status image"
							width={30}
							height={30}
						/>

						<small className={styles.profileStatusTitle}>
							{props.status.title}
						</small>
					</div>

				</div>

				<div className={styles.personalDescription}>
					<h1 className={styles.title}>
						Bem-vindo ao meu portfólio!
					</h1>

					<p>
						Olá, meu nome é Leonardo.
						Eu sou estudante de Ciência da Computação na {' '}
						<i>UFV-CAF</i> e apaixonado por desenvolvimento web moderno.
					</p>

					<h2>Entre em contato:</h2>
					<div className={styles.contacts}>
						{
							CONTACT_LIST.map((contact, index) => (
								<Badge
									src={contact.src}
									alt={contact.alt}
									href={contact.href}
									key={`${index}`}
								/>
							))
						}
					</div>

				</div>
			</div>
			
			<h2 className={styles.technologies}>
				Tecnologias
			</h2>

			<SkillsContainer
				skills={props.skills}
			/>

			<ProjectList
				projects={props.projects}
			/>

			<PostList>
				{
					props.posts.map((p, index) => (
						<MiniPostCard
							key={index}
							title={p.title}
							date={p.date}
							subheading={p.subheading}
							href={p.href}
						/>
					))
				}
			</PostList>
			
		</main>
	  </Container>
  );
};

export const getServerSideProps = async () => {
	const avatarUrl = await getGithubProfilePic();
	
	const posts = await getAllPostPreviewsAsMiniPosts();
	const skills = await getAllSkills();
	const projects = await getAllProjects();
	const status = await getSingleRandomStatus();

	return {
		props: {
			avatarUrl: avatarUrl || '',
			posts,
			skills,
			projects,
			status,
		},
	};
};

export default Home;

