// next
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

// styles
import styles from '../styles/Home.module.css';

// components
import Container from '../components/Container';
import PostList from '../components/PostList';
import SimpleCard from '../components/SimpleCard';
import SkillsContainer from '../components/SkillsContainer';

// libs
import { getGithubProfilePic } from '../libs/info';
import { DefaultProps, MiniPost, Skill } from '../libs/types';

// data consumption
import { getAllPostPreviewsAsMiniPosts } from '../libs/post';
import { getAllSkills } from '../libs/skills';

interface Props extends DefaultProps {
	avatarUrl?: string;
	posts: MiniPost[];
	skills: Skill[];
};

const Home: NextPage<Props> = (props) => {
  return (
	<Container>
		<Head>
			<title>Leo's Portfolio</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main className={styles.main}>
			<div className={styles.personalInfo}>
				{
					props.avatarUrl
					? (
						<Image
							className={styles.profilePic}
							src={props.avatarUrl}
							alt="Leo's Github profile picture"
							width="200px"
							height="200px"
						/>
					)
					: null
				}

				<div className={styles.personalDescription}>
					<p>
						Hello, I'm Leonardo.
						I'm a CS Student at <i>UFV-CAF</i> (Brazil)
						who's passionate about modern Web Development.
					</p>
				</div>
			</div>
			
			<h1 className={styles.title}>
				Welcome to my portfolio!
			</h1>

			<SkillsContainer
				skills={props.skills}
			/>

			<PostList>
				{
					props.posts.map(p => (
						<SimpleCard
							title={p.title}
							date={p.date}
							subheading={p.subheading}
							href={p.href}
						/>
					))
				}
			</PostList>
			
		</main>
	  </Container>
  );
};

export const getStaticProps = async () => {
	const avatarUrl = await getGithubProfilePic();
	
	const posts = await getAllPostPreviewsAsMiniPosts();
	const skills = await getAllSkills();

	return {
		props: {
			avatarUrl: avatarUrl || '',
			posts,
			skills,
		},
	};
};

export default Home
